version: '3'

services:
    next:
        container_name: next
        build: ./services/next
        image: next:ts
        volumes:
            - next:/usr/app/srcs
        networks:
            - my_network
        env_file:
            - ./env/.env
        ports:
            - '4242:4242'
        restart: always
        depends_on:
            - nest
            - postgresql

    nest:
        container_name: nest
        build: ./services/nest
        image: nest:ts
        volumes:
            - nest:/usr/app/srcs
        networks:
            - my_network
        env_file:
            - ./env/.env
        ports:
            - '3000:3000'
        restart: always
        depends_on:
            - postgresql

    postgresql:
        container_name: postgresql
        build:
            context: ./services/postgresql
            args:
                - DB_NAME=${DB_NAME}
                - POSTGRES_USER_ID=${POSTGRES_USER_ID}
                - POSTGRES_USER_PASSWORD=${POSTGRES_USER_PASSWORD}
        image: db:ts
        expose:
            - '5432'
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        env_file:
            - ./env/.env
        networks:
            - my_network
        restart: always

volumes:
    next:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: '${PWD}/srcs/next'
    nest:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: '${PWD}/srcs/nest'
    db:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: '${PWD}/srcs/postgresql'

networks:
    my_network:
        driver: bridge
